{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "phpmyadmin.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "phpmyadmin.labels" . | nindent 4 }}
  {{- $annotations := include "phpmyadmin.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "phpmyadmin.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    {{- if .Values.networkPolicy.allowExternal }}
    - Egress
    {{- end }}
  ingress:
    {{- if .Values.networkPolicy.allowExternal }}
    - {}
    {{- else }}
    {{- if .Values.networkPolicy.ingressNSMatchLabels }}
    - from:
        - namespaceSelector:
            matchLabels:
              {{- range $key, $value := .Values.networkPolicy.ingressNSMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
        - podSelector:
            matchLabels: {}
      ports:
        - port: {{ .Values.containerPorts.http }}
          protocol: TCP
    {{- end }}
    {{- if .Values.networkPolicy.ingressNSPodMatchLabels }}
    - from:
        - namespaceSelector:
            matchLabels:
              {{- range $key, $value := .Values.networkPolicy.ingressNSMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
        - podSelector:
            matchLabels:
              {{- range $key, $value := .Values.networkPolicy.ingressNSPodMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
      ports:
        - port: {{ .Values.containerPorts.http }}
          protocol: TCP
    {{- end }}
    {{- range .Values.networkPolicy.customRules }}
    - {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
  {{- if not .Values.networkPolicy.allowExternal }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- if .Values.networkPolicy.extraEgress }}
    {{- include "phpmyadmin.tplValue" (dict "value" .Values.networkPolicy.extraEgress "context" .) | nindent 4 }}
    {{- end }}
    # Allow connection to database
    {{- if .Values.networkPolicy.databaseSelector }}
    - to:
        - podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.databaseSelector | nindent 14 }}
      ports:
        - port: {{ include "phpmyadmin.databasePort" . }}
          protocol: TCP
    {{- else }}
    # Allow connection to any pod on database port (less secure but more flexible)
    - to: []
      ports:
        - port: {{ include "phpmyadmin.databasePort" . }}
          protocol: TCP
    {{- end }}
  {{- end }}
{{- end }}
