{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "phpmyadmin.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "phpmyadmin.labels" . | nindent 4 }}
  {{- $annotations := include "phpmyadmin.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "phpmyadmin.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  egress:
    # Allow all egress traffic by default
    - {}
    {{- if .Values.networkPolicy.customEgressRules }}
    {{- range .Values.networkPolicy.customEgressRules }}
    - {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
  ingress:
    # Allow all ingress traffic to container ports
    - ports:
        - port: {{ .Values.containerPorts.http }}
          protocol: TCP
    {{- if .Values.networkPolicy.customIngressRules }}
    {{- range .Values.networkPolicy.customIngressRules }}
    - {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
{{- end }}
