{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "phpmyadmin.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "phpmyadmin.labels" . | nindent 4 }}
  {{- if or .Values.persistence.annotations (include "phpmyadmin.annotations" .) }}
  annotations:
    {{- if (include "phpmyadmin.annotations" .) }}
    {{- include "phpmyadmin.annotations" . | nindent 4 }}
    {{- end }}
    {{- with .Values.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.persistence.selector }}
  selector: {{- include "phpmyadmin.tplValue" (dict "value" .Values.persistence.selector "context" .) | nindent 4 }}
  {{- end }}
{{- end }}
