{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "phpmyadmin.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "phpmyadmin.labels" . | nindent 4 }}
  {{- $annotations := include "phpmyadmin.annotations" . }}
  {{- if or .Values.serviceAccount.annotations $annotations }}
  annotations:
    {{- if $annotations }}
    {{- $annotations | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
